using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using XrmToolBox.Extensibility;
using XrmToolBox.Extensibility.Interfaces;

namespace Cinteros.Xrm.FetchXmlBuilder
{
    [Export(typeof(IXrmToolBoxPlugin)),
       ExportMetadata("Name", "FetchXML Builder"),
       ExportMetadata("Description", "Build and test FetchXML with all capabilities supported by the CRM platform"),
       ExportMetadata("SmallImageBase64", "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAB3RJTUUH3wYQCTsMyjA++QAAAAlwSFlzAAAKjAAACowBvcbP2AAAAB5QTFRF/wAAAAAA////9/f33t7e5+fnnJychISE1tbWxsbGVCYGswAAAAF0Uk5TAEDm2GYAAACsSURBVHjafZNbFsIwCESBqNX9b9hUShle8pHTw9zyCIGIb6PT9ESLgHET4JECkOERiNVkLybjFmDuCS9/IAaAE8B8yDbV9CsAp/tjgJEA6I9LBY9UGtnKAh1jOPGD0vzAVtR9PhijdJt0kTePOXaG1yaOfFugP/hZuzBC7ntY3cT8ArATIMAtc5ZUfx57mXatY34VEzGsCLUpcC9M6Lbomk8foXnCVIg/O9baF0ebAvCCdlGCAAAAAElFTkSuQmCC"),
       ExportMetadata("BigImageBase64", "iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAMAAABHPGVmAAADAFBMVEX/AAAAAADO1tb////39/fv7+/e3t57hITOzs6EhISlpaW1tbW9vb3n5+fGxsatra3W1taMjIyUlJScnJz3AACEnJwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADOO1bPAAABAHRSTlMA////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////Cpf0PAAAAAlwSFlzAAAKnQAACp0BJpU99gAAAu1JREFUeJzl2dty4yAMBuB6wWka59A0s+//qpumTZFAh18Yz+xMuYuN+BwOMgkvL7+mTNOgZuwyRI0hAjtCEepuiyhdOBTR+nAkonbiQETvxQCi3NSeZSDS1OpUoCB7tMYgznANQWQjovgRmhFQ5AB17vYpXrxlwIoTbhuoYkd7BqiYwb6BKVYsYkCKEYoZiKJHogagyBXvn3HDV7R6EcNVlGoxA31TrDPAV8VKA3tX8Gu7lGZW0pk3mTO7nfNf5GVRX1oSK4f6wc/s9s3+Li3yfeEt5dLIvu2ecjMnr8ca5KeVD6LsDOTH0JX6PmnmQJRrbZwEQ1Wq21W/F6UyzsVgPoJUTb2TsWU3liefv8bcUdjNuk+muSAzuXwrxlKHGIaW28kMK4N/Lca5DbEQJe+SYTm3196lEGX05b6qWszpUhsnOSRskOWS08fDEIcJUrT603QhykRHKesxUYOnqbIIm6XjKlb9R05uSjYNZ46JZRaMNycmatDBZnMgoPgGWy50NsMKYtTf5QjFRI17uiJFSCamAlafpj08sRoFrs5n2EZKNbtCBqpkjmipUTEw5ZTqIiZ51UCUNq9kYBbHVuO+MT6VZr9nGp5yJLuGG8n7dvaKZcgD2zUc+dslYFgK2Ug+NqvqNsk1dIVsib+3K2SmqctFNvx9RFkaZM2M2UkUI0sXpe1+eE9EHlqkxReLZVi71GomXettUuTrVPXknwef5YJMZEghk7VZd2WbtE4hv06EjifpTM/7rrIIk5cWMifC29WnspBeFxNuWZNZ+kmJKDzxCqnwwCrMvEkfuVf5k/h/Ae2j7uo/E+ZX6RhER7r+9Yif56w1+k8AAkb3WcYGyMp/1TCjd/QteRvFNwYoCLJWgYzfpWx7iPNsRG4uiHhnWkpz4xSjtSiCHRYpQTBinpgOQ6yz31HdJSpOaz1IozittfU6FPuRxYphRcXVLxxXNHsA0nFoFDeeDcryKOOrxa2NxyEnivQS/2/5B565IlAXmi3EAAAAAElFTkSuQmCC"),
       ExportMetadata("BackgroundColor", "#FFFFFF"), // Use a HTML color name
       ExportMetadata("PrimaryFontColor", "#000000"), // Or an hexadecimal code
       ExportMetadata("SecondaryFontColor", "Blue")]
    public partial class FetchXMLBuilderPlugin : PluginBase
    {
        public override IXrmToolBoxPluginControl GetControl()
        {
            return new FetchXmlBuilder();
        }
    }
}
